spring.application.name=rating-data-service
server.port=4547
spring.config.import=optional:configserver:http://${CONFIG_SERVER_URL:localhost}:4542
eureka.instance.hostname=eureka-0
eureka.instance.prefer-ip-address=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
#eureka.client.serviceUrl.defaultZone=${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
eureka.client.serviceUrl.defaultZone=http://eureka-0.eureka.default.svc.cluster.local:8761/eureka